### ISSUE TITLE
Editor Height

### ISSUE THREAD

**Issue by 2braincells2go** [cristoslc/Wondertron#2]
Pretty cool mod you have here! Been looking for one like yours to learn from.

I cannot seem to find the CSS (guessing css controlled) for the editor toolbar. When using the far left dropdown menu for text formatting is cut off. Can barely see the top of it. Like to make area taller.

Any ideas?

BTW: what version of WCMS is your Wondertron based on?

Many thanks!

Woody

**Comment by cristoslc** [comment]
@2braincells2go: The editor toolbar height is set somewhere in WonderCMS...I see the issue you described, but unfortunately I'm not sure where the source lies. You might try using Chrome Developer Tools or FireBug to identify the class on the editing toolbar, then add an override for that class to `wondertron.css`.

Unfortunately, I don't have time to maintain this project anymore (and WonderCMS itself appears to have been abandoned by its author -- last commit from them was in 2014). But if you find and test a fix, I am happy to merge a pull request, or to transfer the repo over to you if you'd like to take ownership.

I don't know for sure, but I think this was built for WonderCMS v0.5. I updated the README to specify that.

Best of luck!
~ Cristos

**Comment by cristoslc** [comment]
Should have read my own README more closely...it's actually designed for v0.6 BETA of WonderCMS. Sorry for the confusion.

**Comment by 2braincells2go** [comment]
Thanks for reaching our and explaining Cristos.

I have dug around in the code and explored with chrome dev tools without luck. It is there somewhere, lol. Will give it another shot.

Wanting to use your version in a classroom project but the button is an issue.

Yes I should have read the readme little closer too, dumb question as answer right in front of me:)

Thanks again.

Woody

**Comment by 2braincells2go** [comment]
You know, this might be a good project to take over and be happy to if you still want to transfer to someone.

**Comment by cristoslc** [comment]
I just submitted the transfer via Github, thanks for your willingness to carry on with the project! Let me know if you have any issues accepting the transfer.

I had a hard time with the inspector also, but after a little sleight-of-hand was able to get closer to the relevant classname: `jqte`. I would start with this search to find the right place to adjust the toolbar height: https://github.com/cristoslc/Wondertron/search?utf8=%E2%9C%93&q=jqte&type=Code

Good luck!

**Comment by cristoslc** [comment]
A few more minutes of searching and found *a* place you can edit it -- just keep in mind that updating WonderCMS will probably overwrite your fix:

In line 87 of `public_html/plugins/jquery-te-1.4.0/jquery-te-1.4.0.css`, change the height of `.jqte_tool.jqte_tool_1 .jqte_tool_label` to be 25 (instead of 16). Don't have time to branch and make a new commit right now, but you should be able to do it pretty easily after the transfer is done.
